### PR TITLE
fix: add getBody to the RequestFields example

### LINKED ISSUE #27: Property 'getBody' is missing in type '{}' but required in type 'ArcjetAdapterContext'
The docs example in https://github.com/arcjet/arcjet-docs/blob/9d790cecc997e8d4b0148b29a8e462ba7c0138ed/src/content/docs/reference/snippets/nodejs/RequestFields.ts#L45 

no longer works with the latest SDK release:

```
 Property 'getBody' is missing in type '{}' but required in type 'ArcjetAdapterContext'.
```

### PR DESCRIPTION
**Pull request by e-moran**
This shows how to use `@arcjet/body` to get the body of a Node.js `IncomingMessage` when manually constructing the request for the SDK.

Closes #27

### CODE REVIEW

File: src/content/docs/reference/snippets/nodejs/RequestFields.ts [hunk 1]
```diff
@@ -41,8 +42,15 @@ const server = http.createServer(async function (
     headers: req.headers,
   };
 
-  // @ts-ignore
-  const decision = await aj.protect({}, details);
+  // Provide a function to get the body in case it is needed by a rule.
+  const getBody = async () => {
+    return await readBody(req, {
+      // Only read up to 1 MiB of the body
+      limit: 1048576,
```
Comment (blaine-arcjet) [inline src/content/docs/reference/snippets/nodejs/RequestFields.ts:49]: Do you want the try/catch around this to return an undefined body in failure cases?

**Review by blaine-arcjet — APPROVED** [review]
